# Gradle
org.gradle.jvmargs=-Xmx1G
org.gradle.daemon=true
org.gradle.parallel=true
org.gradle.caching=true
org.gradle.configuration-cache=true

# Parchment
parchment_minecraft_version=1.21.1
parchment_mappings_version=2024.11.17

# Minecraft
minecraft_version=1.21.1
minecraft_version_range=[1.21.1]

# NeoForge
neo_version=21.1.248
loader_version_range=[1,)

# Mod
mod_id=improvedadvancements
mod_name=Improved Advancements
mod_author=Fooze
mod_description=A Minecraft mod that improves the advancement screen.
mod_version=1.0.0
mod_license=MIT
mod_display_url=https://modrinth.com/project/improved-advancements/
mod_issues_url=https://github.com/Foozey/Improved-Advancements/issues
mod_logo=improvedadvancements.png
mod_group_id=com.fooze.improvedadvancements